# Generated by Django 5.2.1 on 2025-10-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending_dispatch", "Pending Dispatch"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending_dispatch",
                        max_length=50,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Deliveries",
            },
        ),
    ]
