# Generated by Django 5.2.1 on 2025-10-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_note",
            field=models.TextField(
                blank=True,
                help_text="A short note about the delivery (e.g., left with neighbor).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="proof_of_delivery_image",
            field=models.ImageField(
                blank=True,
                help_text="Image proof that the delivery was successfully completed.",
                null=True,
                upload_to="proofs_of_delivery/%Y/%m/%d/",
            ),
        ),
    ]
