# Generated by Django 5.2.1 on 2025-10-10 06:50

import apps.orders.models
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManualOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_order_id",
                    models.CharField(
                        default=apps.orders.models.generate_unique_manual_order_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer or company name", max_length=255
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "order_source",
                    models.CharField(
                        choices=[
                            ("b2b", "B2B Client"),
                            ("phone", "Phone Order"),
                            ("email", "Email Order"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="b2b",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        help_text="Direct address entry for manual orders"
                    ),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHECK", "Check"),
                            ("CREDIT_TERMS", "Credit Terms (NET 30)"),
                        ],
                        default="COD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this order",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock_deducted", models.BooleanField(default=False)),
                ("stock_deducted_at", models.DateTimeField(blank=True, null=True)),
                ("stock_restored", models.BooleanField(default=False)),
                ("stock_restored_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Manual Order",
                "verbose_name_plural": "Manual Orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="ManualOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_at_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Manual Order Item",
                "verbose_name_plural": "Manual Order Items",
                "ordering": ["added_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=apps.orders.models.generate_unique_order_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("COD", "Cash on Delivery")],
                        default="COD",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stock_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if stock has been deducted for this order",
                    ),
                ),
                (
                    "stock_deducted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when stock was deducted",
                        null=True,
                    ),
                ),
                (
                    "stock_restored",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if stock was restored (e.g., order canceled)",
                    ),
                ),
                (
                    "stock_restored_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when stock was restored",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_at_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["added_at"],
            },
        ),
    ]
