# Generated by Django 5.2.1 on 2025-10-10 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manualorder",
            name="created_by",
            field=models.ForeignKey(
                help_text="Staff who created this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_manual_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manualorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to user account if exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manualorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.manualorder",
            ),
        ),
        migrations.AddField(
            model_name="manualorderitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_order_items",
                to="store.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer who placed this order. Address info comes from their CustomerProfile.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="store.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="manualorderitem",
            unique_together={("order", "product_variant")},
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product_variant")},
        ),
    ]
