# Generated by Django 5.2.1 on 2025-10-11 17:49

from django.db import migrations, models


def populate_default_names(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(first_name="", last_name=""):
        user.first_name = user.username
        user.last_name = "(Please Update)"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualorder",
            name="gcash_reference_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payment_proofs/gcash/manual/",
                verbose_name="GCash Payment Proof",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gcash_reference_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payment_proofs/gcash/customer/",
                verbose_name="GCash Payment Proof",
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("GCASH", "GCash Transfer")],
                default="COD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("GCASH", "GCash Transfer")],
                default="COD",
                max_length=10,
            ),
        ),
    ]
