# Generated by Django 5.2.1 on 2025-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualorder',
            name='order_source',
            field=models.CharField(choices=[('b2b', 'B2B Client'), ('phone', 'Phone Order'), ('email', 'Email Order'), ('walk_in', 'Walk-in')], default='b2b', max_length=20),
        ),
    ]
