# Generated by Django 5.2.1 on 2025-10-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("user_registration", "User Registered"),
                            ("supplier_approval", "Supplier Approved"),
                            ("order_placed", "Order Placed"),
                            ("order_status_change", "Order Status Changed"),
                            ("payment_received", "Payment Received"),
                            ("delivery_completed", "Delivery Completed"),
                        ],
                        help_text="Type of action or event recorded.",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount involved in the transaction (e.g., payment, order total).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the transaction occurred.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief explanation or context for the transaction.",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order related to this transaction, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
