# Generated by Django 5.2.1 on 2025-10-18 16:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="order",
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="PHP", max_length=8),
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("adjustment", "Adjustment"),
                ],
                default="payment",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("cancel", "Cancel"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("object_repr", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="transaction_action_f9fa5a_idx"
                    ),
                    models.Index(
                        fields=["user"], name="transaction_user_id_72b613_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="transaction_content_4947d7_idx",
                    ),
                ],
            },
        ),
    ]
