# Generated by Django 5.2.1 on 2025-10-18 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_manualorder_gcash_reference_image_and_more"),
        ("transactions", "0003_alter_transaction_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="reference",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief explanation or context for the transaction.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The order related to this transaction, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount involved in the transaction (e.g., payment, order total).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the transaction occurred.",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("user_registration", "User Registered"),
                    ("supplier_approval", "Supplier Approved"),
                    ("order_placed", "Order Placed"),
                    ("order_status_change", "Order Status Changed"),
                    ("payment_received", "Payment Received"),
                    ("delivery_completed", "Delivery Completed"),
                ],
                help_text="Type of action or event recorded.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                help_text="The user primarily associated with this transaction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
