# Generated by Django 5.2.1 on 2025-10-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
