# Generated by Django 5.2.1 on 2025-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_restocklog_options_alter_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reorder_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
