# Generated by Django 5.2.1 on 2025-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
    ]
