# Generated by Django 5.2.1 on 2025-10-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase_orders", "0001_initial"),
        ("store", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="users.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="store.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseordernotification",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together={("purchase_order", "product_variant")},
        ),
    ]
