# Generated by Django 5.2.1 on 2025-10-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who created the PO request.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("tbd", "To Be Determined"),
                    ("cod", "Cash on Delivery (COD)"),
                    ("net_30", "Net 30 Days (Pay Later)"),
                    ("prepaid", "Pre-Paid"),
                ],
                default="tbd",
                help_text="Final agreed upon payment method.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (Internal)"),
                    ("request_pending", "Request Pending Price"),
                    ("supplier_priced", "Supplier Price Submitted"),
                    ("confirmed", "Confirmed & Ready for Shipping"),
                    ("in_transit", "In Transit (OTW)"),
                    ("received", "Received & Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
