# Generated by Django 5.2.1 on 2025-10-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_product_reorder_level"),
        ("purchase_orders", "0003_purchaseorder_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="inventory.product",
            ),
        ),
    ]
