# Generated by Django 5.2.1 on 2025-10-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_purchaseorderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
