# Generated by Django 5.2.1 on 2025-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0005_alter_purchaseorderitem_unit_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (Internal)"),
                    ("request_pending", "Request Pending Price"),
                    ("supplier_priced", "Supplier Price Submitted"),
                    ("confirmed", "Confirmed & Ready for Shipping"),
                    ("in_transit", "In Transit (OTW)"),
                    ("received", "Received & Completed"),
                    ("partially_received", "Partially Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
