# Generated by Django 5.2.1 on 2025-11-07 18:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be refunded', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for refund/return request', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Internal)'), ('request_pending', 'Request Pending Price'), ('supplier_priced', 'Supplier Price Submitted'), ('confirmed', 'Confirmed & Ready for Shipping'), ('in_transit', 'In Transit (OTW)'), ('received', 'Received & Completed'), ('partially_received', 'Partially Received'), ('refund', 'Refund/Return Requested'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
