# Generated by Django 5.2.1 on 2025-11-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_purchaseorder_refund_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', help_text='Payment status - automatically managed based on payment method, status, and due dates', max_length=25),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified/confirmed', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff who verified/approved the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_po_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
