# Generated by Django 5.2.1 on 2025-11-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_purchaseorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', help_text='Payment status - automatically managed', max_length=25),
        ),
    ]
