# Generated by Django 5.2.1 on 2025-11-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0009_alter_purchaseorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_proof_image',
            field=models.ImageField(blank=True, help_text='Proof of payment (receipt, screenshot, etc.)', null=True, upload_to='payment_proofs/po/%Y/%m/%d/'),
        ),
    ]
